// AETHER Neural Interface — Service Worker v5.37 · GPL-3.0 · Composer Float
const CACHE_VERSION='aether-v5.37.0',STATIC_CACHE=`${CACHE_VERSION}-static`,CDN_CACHE=`${CACHE_VERSION}-cdn`,DYNAMIC_CACHE=`${CACHE_VERSION}-dynamic`;
const CORE_ASSETS=[
  './','./index.html','./script.js','./style.css','./style-ivory.css','./manifest.json','./logo.svg',
  './core/version.js','./core/safe-math.js','./core/capabilities.js','./core/beast-mode.js','./core/skill-utils.js','./core/aether-skills-pack.js','./core/aether-skill-runtime.js','./core/aether-deep-research.js','./core/vendor-loader.js',
  './core/kernel.js','./core/aether-security.js','./core/aether-tool-runtime.js','./core/aether-rag-v2.js','./core/soul-os.js','./core/model-council.js','./core/thread-graph.js',
  './core/ghost-commits.js','./core/aether-code-pro.js','./core/aether-subagents.js','./core/aether-changeset.js','./core/aether-tool-packs.js',
  './core/aether-mcp-bridge.js','./core/aether-git-lite.js','./core/aether-code-mobile.js','./core/cognition-theater.js','./core/themes.js','./core/boot-cinematic.js',
  './core/aether-moat.js','./core/aether-ship.js','./core/aether-markdown.js','./core/aether-composer-float.js','./core/advanced-bridge.js',
  './discovery-skill.js','./documents-supremacy.js','./vendor/README.md'
];
const CDN_DOMAINS=['cdn.jsdelivr.net','cdnjs.cloudflare.com','cdn.katex.org','huggingface.co','unpkg.com','esm.sh'];
const BYPASS=['api.openai.com','api.anthropic.com','generativelanguage.googleapis.com','googleapis.com','accounts.google.com','api.deepseek.com','dashscope.aliyuncs.com','api.groq.com','api.x.ai','api.mistral.ai','openrouter.ai','api.moonshot.ai','api.together.xyz','api.siliconflow.cn','api.perplexity.ai','api.cohere.com','api.fireworks.ai','api.bfl.ml','api.moondream.ai','api.firecrawl.dev','api.tavily.com','api.search.brave.com','hooks.slack.com','api.notion.com','api.atlassian.com','gitlab.com','api.github.com','speech.googleapis.com','api.openweathermap.org','api.guerrillamail.com','nominatim.openstreetmap.org','calendar.googleapis.com','oauth2.googleapis.com','localhost','127.0.0.1'];
self.addEventListener('install',e=>{console.log('[AETHER SW] Installing v5.37 Composer Float');e.waitUntil(caches.open(STATIC_CACHE).then(c=>Promise.allSettled(CORE_ASSETS.map(u=>c.add(u).catch(()=>{}))).then(()=>self.skipWaiting())));});
self.addEventListener('activate',e=>{console.log('[AETHER SW] Activating v5.37');e.waitUntil(caches.keys().then(ks=>Promise.all(ks.filter(k=>k.startsWith('aether-')&&!k.startsWith(CACHE_VERSION)).map(k=>caches.delete(k)))).then(()=>self.clients.claim()));});
self.addEventListener('fetch',e=>{const{request:req}=e;const url=new URL(req.url);if(req.method!=='GET')return;if(BYPASS.some(d=>url.hostname.includes(d)||req.url.includes(d)))return;if(CDN_DOMAINS.some(d=>url.hostname.includes(d))){e.respondWith(cacheFirst(req,CDN_CACHE));return;}if(url.origin===self.location.origin){e.respondWith(swr(req,STATIC_CACHE));return;}e.respondWith(netFirst(req,DYNAMIC_CACHE));});
async function cacheFirst(req,cn){const c=await caches.match(req);if(c)return c;try{const r=await fetch(req);if(r.ok)(await caches.open(cn)).put(req,r.clone());return r;}catch{return new Response('Offline',{status:503});}}
async function swr(req,cn){const cache=await caches.open(cn);const c=await cache.match(req);const f=fetch(req).then(r=>{if(r.ok)cache.put(req,r.clone());return r;}).catch(()=>null);return c||await f||new Response('Offline',{status:503});}
async function netFirst(req,cn){try{const r=await fetch(req);if(r.ok)(await caches.open(cn)).put(req,r.clone());return r;}catch{return await caches.match(req)||new Response('Offline',{status:503});}}
self.addEventListener('push',e=>{const d=e.data?.json()||{};e.waitUntil(self.registration.showNotification(d.title||'⬡ AETHER',{body:d.body||'',icon:'./logo.svg',badge:'./logo.svg',tag:d.tag||'aether',data:d,vibrate:[200,100,200],actions:[{action:'view',title:'View'},{action:'dismiss',title:'Dismiss'}]}));});
self.addEventListener('notificationclick',e=>{e.notification.close();if(e.action==='dismiss')return;e.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(cs=>{const ex=cs.find(c=>c.url.includes('index.html'));if(ex)return ex.focus();return clients.openWindow('./index.html?action=notification');}).catch(()=>{});});
self.addEventListener('sync',e=>{if(e.tag==='aether-scheduled-check')e.waitUntil(clients.matchAll({type:'window'}).then(cs=>Promise.all(cs.map(c=>c.postMessage({type:'SCHEDULED_CHECK'})))));});
self.addEventListener('periodicsync',e=>{if(e.tag==='aether-morning-check')e.waitUntil(clients.matchAll({type:'window'}).then(cs=>{if(cs.length>0)return Promise.all(cs.map(c=>c.postMessage({type:'PERIODIC_CHECK'})));return self.registration.showNotification('⬡ AETHER Check-in',{body:'Your morning report and scheduled tasks are ready.',icon:'./logo.svg',badge:'./logo.svg',tag:'aether-periodic'});}));});
self.addEventListener('message',e=>{const{type,payload}=e.data||{};const port=e.ports[0];if(type==='SKIP_WAITING')self.skipWaiting();if(type==='GET_VERSION')port?.postMessage({version:CACHE_VERSION});if(type==='CLEAR_CACHE')caches.keys().then(ks=>Promise.all(ks.map(k=>caches.delete(k)))).then(()=>port?.postMessage({ok:true}));if(type==='CACHE_URL'&&payload?.url)caches.open(CDN_CACHE).then(c=>c.add(payload.url).catch(()=>{}));if(type==='SHOW_NOTIFICATION'&&payload)self.registration.showNotification(payload.title||'⬡ AETHER',{body:payload.body||'',icon:'./logo.svg',badge:'./logo.svg',tag:payload.tag||'aether-sw'});});
console.log('[AETHER SW] Loaded ⬡ v5.37 · Composer Float · GPL-3.0');
